### ISSUE TITLE
Add "Add Control" button to Cause page

### ISSUE THREAD

**Issue by brysbra** [FraunhoferCESE/HazardTrackingSystem#256]
"Add Control" button from inside existing Cause doesn't work.
This functionality was a pain to implement because of the multi-select, checkout old controls js file.

**Comment by llayman** [comment]
Deffering this for now. The button isn't that critical, and the current architecture would require some very ugly workarounds to make this happen.

**Comment by llayman** [comment]
This issue was moved to FraunhoferCESE/hts-issues#3
