### ISSUE TITLE
Hazard page risk matrix no long working

### ISSUE THREAD

**Issue by brysbra** [FraunhoferCESE/HazardTrackingSystem#258]
Risk Matrix:
Need to double-check if everything still works here. I would think transferred Causes are not showing up right now (depend on REST service calls).

**Comment by llayman** [comment]
Verified as buggy.
* All links are broken within the table.
* Not showing deleted transfers (hazard or cause)
* Not showing risk category/likelihood for transfers

**Comment by llayman** [comment]
+
+#*
+       1. Handle transfers
+               a. Handle transfers whose targets are hazards (deleted or live)
+               b. Handle transfers whose targets are causes
+                       i) Handle transfers whose targets are causes missing likelihood or category (deleted or live)
+                       ii) Handle transfers who targets are causes with both likelihood or category (deleted or live)
+       2. Handle non-transfers
+               a. Handle causes missing likelihood or category (deleted or live)
+               b. Handle causes with likelihood or category (deleted or live)
+*#
+
+#foreach($cause in $hazard.getHazardCauses())
+       #if($cause.getTransfer() != 0)
